---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: ingress-nginx
  name: nginx-ingress-custom
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/component: controller
  namespaceSelector:
    matchNames:
    - ingress-nginx
  endpoints:
  - port: prometheus
    interval: 5s
