name: "Create cluster using KinD"
on:
  push:
    branches:
      - main
jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.11.1"
      - name: Deploying
        run: |
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}
      - name: Deploy hyphen-application
        run: 
          cd 02-ingress-deployment && kubectl apply -f ingress_kind.yaml
      - run:
          cd 03-echo-http-deployment && kubectl apply -f hashicorp_http.yaml
      - run:
          cd 04-monitoring-setup && kubectl apply -f servicemonitor.yaml
