on: pull_request
name: Validate
jobs:
  kubeval:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: test
      uses: instrumenta/kubeval-action@master
      with:
        files: 02-kuberenetes-deployment/
